// Shared Android entry activity generated by Flutter.
// Leave this minimal unless a feature requires native Android integration.
// The Kotlin package must remain consistent with Android namespace and application configuration.

// Explains: Place the native activity in the Android namespace matching the app configuration.
package com.linkworks.linkworks

// Explains: Import the local file needed by this implementation; keep the referenced path valid when moving files.
import io.flutter.embedding.android.FlutterActivity

// Explains: Define the named type and the methods that implement its documented responsibility.
class MainActivity : FlutterActivity()
