// Shared Android build plugin setup, generated by Flutter and amended by FlutterFire.
// Change plugin versions here only as part of a coordinated Flutter/Android upgrade.
// local.properties supplies this device SDK path and must remain untracked.

// Explains: Locate the Flutter SDK and configure plugin resolution before building the app.
pluginManagement {
    // Explains: Resolve the Flutter SDK path once and use it to load Flutter Gradle tooling.
    val flutterSdkPath =
        // Explains: Compute and return the SDK path using the enclosed local-properties lookup.
        run {
            // Explains: Prepare to read the machine-local Flutter SDK path from local.properties.
            val properties = java.util.Properties()
            // Explains: Load local SDK properties and close the file stream after reading.
            file("local.properties").inputStream().use { properties.load(it) }
            // Explains: Read the Flutter SDK installation path used for this machine build.
            val flutterSdkPath = properties.getProperty("flutter.sdk")
            // Explains: Fail early if the required local Flutter SDK setting is absent.
            require(flutterSdkPath != null) { "flutter.sdk not set in local.properties" }
            // Explains: Return the verified SDK path from this configuration block.
            flutterSdkPath
        // Explains: Close the preceding argument list, collection, or code block; no additional action runs here.
        }

    // Explains: Load Flutter Gradle tooling from the configured SDK installation.
    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    // Explains: List repositories Gradle may use to resolve Android dependencies.
    repositories {
        // Explains: Resolve Android and Firebase artifacts from Google Maven.
        google()
        // Explains: Resolve general JVM dependencies from Maven Central.
        mavenCentral()
        // Explains: Resolve Gradle plugins through the official plugin portal.
        gradlePluginPortal()
    // Explains: Close the preceding argument list, collection, or code block; no additional action runs here.
    }
// Explains: Close the preceding argument list, collection, or code block; no additional action runs here.
}

// Explains: Declare the build plugins applied to this Android project.
plugins {
    // Explains: Select the named build plugin/version; apply false makes it available without applying it to this project.
    id("dev.flutter.flutter-plugin-loader") version "1.0.0"
    // Explains: Select the named build plugin/version; apply false makes it available without applying it to this project.
    id("com.android.application") version "9.1.0" apply false
    // START: FlutterFire Configuration
    // Explains: Select the named build plugin/version; apply false makes it available without applying it to this project.
    id("com.google.gms.google-services") version("4.4.4") apply false
    // END: FlutterFire Configuration
    // Explains: Select the named build plugin/version; apply false makes it available without applying it to this project.
    id("org.jetbrains.kotlin.android") version "2.4.0" apply false
// Explains: Close the preceding argument list, collection, or code block; no additional action runs here.
}

// Explains: Include the Android app module in this Gradle build.
include(":app")
